apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: c3s-charts
  namespace: flux-system
spec:
  interval: 30m
  url: oci://eccr.ecmwf.int/c3s-applications/wms-ready-application
  ref:
    tag: 0.1.4
  secretRef:
    name: harbor-pull-secret
