apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: c3s-charts
  namespace: flux-system
spec:
  interval: 30m
  url: oci://eccr.ecmwf.int/c3s-applications
  secretRef:
    name: harbor-pull-secret
